---
driver:
  name: vagrant
  synced_folders:
    - ['.', '/tmp/awscli', type: 'rsync']

provisioner:
  name: chef_zero

platforms:
  - name: macos-10.12

suites:
  - name: default
    run_list: awscli-omnibus
    attributes:
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_user_password: vagrant
        install_dir: /opt/awscli
